name: Open a PR for a new release

on:
  workflow_dispatch:
    inputs:
      crate:
        description: Which crate to release
        required: true
        type: choice
        options:
          - neo4rs
          - neo4rs-macros
      version:
        description: >-
          What version to release.
          Can be one of 'major', 'minor', 'patch', or a concrete version.
          See https://github.com/crate-ci/cargo-release/blob/7527065e413b9625ccb09800b765f6c49d011c79/docs/reference.md#bump-level for more details.
        required: true
        type: string

env:
  RUSTUP_TOOLCHAIN: stable
  MSRV: 1.75.0

jobs:
  make-release-pr:
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: chainguard-dev/actions/setup-gitsign@main

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Set up Rust nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Set up Rust MSRV
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.MSRV }}

      - name: Set up Rust stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install cargo-semver-checks
        uses: taiki-e/install-action@cargo-semver-checks

      - name: Install cargo-workspaces
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-workspaces

      - name: Install cargo-release
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-release

      - uses: cargo-bins/release-pr@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          crate-name: ${{ inputs.crate || 'neo4rs' }}
          check-semver: true
          base-branch: main
